### ISSUE TITLE
How do polyfilled selector specificities compare to native ones?

### ISSUE THREAD

**Issue by guiprav** [PM5544/scoped-polyfill#9]
I have a question: Don't CSS selectors generated by this polyfill have higher specificity than their native counterparts due to the added ID?

I ask this not to be a prick, but because that fact might actually cause web site appearances to change depending on whether the polyfill is active or not (in other words, depending on user agent support to scoped CSS or lack thereof).

I think if this is the case, the README file should mention it, no?

Thanks for the great lib :)

**Comment by PM5544** [comment]
The added id is a way to mimic the native behaviour of the stylesheet with the scoped attribute.
It seemed like the best choice because specificity works in all browsers that support basic CSS.
And inside a scoped stylesheet all the styles are more specific than their "outside" counterparts so adding an id makes it work the same way.
And the extra id also make the styles only match the elements inside the container with that id attribute so they will no have styling any effect on the "outside". 

Does this clarify enough?

**Comment by guiprav** [comment]
Oh, sure, I thought native scoped CSS had the same selector specificities as the global ones, but you're right, they don't. I guess adding an ID is the best way to emulate native behavior. It's not exactly the same, but I guess the difference would only affect very corner cases (i.e. selectors with 2 IDs). Thanks!
